const cfg=window.AXOMPREP_CONFIG; const client=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey); const $=id=>document.getElementById(id);
function msg(id,text,hide=false){const e=$(id);e.textContent=text;e.classList.toggle('hidden',hide)}
async function init(){const {data:{user}}=await client.auth.getUser(); if(!user){$('authMessage').textContent='Please log in with your AxomPrep account.';return} const {data:profile,error}=await client.from('profiles').select('role,full_name').eq('id',user.id).maybeSingle(); if(error||profile?.role!=='admin'){$('authMessage').textContent='Your account does not have admin access yet.';return} $('authState').classList.add('hidden');$('adminApp').classList.remove('hidden');$('adminUser').textContent=profile.full_name||user.email; await Promise.all([loadOptions(),loadQuestions(),loadStats(),loadCurrent()]);}
$('loginAdmin').onclick=()=>{sessionStorage.setItem('axomprep_admin_return','/admin');location.href='/#login'}; $('logoutBtn').onclick=async()=>{await client.auth.signOut();location.href='index.html'};
async function loadOptions(){const [e,s]=await Promise.all([client.from('exams').select('id,name').order('name'),client.from('subjects').select('id,name').order('name')]); $('exam').innerHTML=(e.data||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('');$('subject').innerHTML=(s.data||[]).map(x=>`<option value="${x.id}">${x.name}</option>`).join('')}
async function loadStats(){const [{count:q}, {count:r},{count:c}]=await Promise.all([client.from('questions').select('*',{count:'exact',head:true}).eq('status','published'),client.from('questions').select('*',{count:'exact',head:true}).in('status',['draft','review']),client.from('current_affairs').select('*',{count:'exact',head:true})]);$('qCount').textContent=q??0;$('reviewCount').textContent=r??0;$('caCount').textContent=c??0}
async function loadQuestions(){const {data}=await client.from('questions').select('id,question,status,exam_id,subject_id,exams(name),subjects(name)').order('created_at',{ascending:false}).limit(50);$('questionRows').innerHTML=(data||[]).map(q=>`<tr><td>${esc(q.question).slice(0,180)}</td><td>${esc(q.subjects?.name||'')}</td><td>${esc(q.exams?.name||'')}</td><td><span class="badge">${q.status}</span></td><td><button class="btn light" onclick="setStatus('${q.id}','published')">Publish</button></td></tr>`).join('')||'<tr><td colspan="5">No questions yet.</td></tr>'}
window.setStatus=async(id,status)=>{const {error}=await client.from('questions').update({status}).eq('id',id);if(error)alert(error.message);else{await loadQuestions();await loadStats()}}
$('questionForm').onsubmit=async e=>{e.preventDefault();const row={question:$('qtext').value,option_a:$('a').value,option_b:$('b').value,option_c:$('c').value,option_d:$('d').value,answer:$('answer').value,explanation:$('explanation').value,exam_id:$('exam').value||null,subject_id:$('subject').value||null,difficulty:$('difficulty').value,year:$('year').value?Number($('year').value):null,tags:$('tags').value,status:$('status').value};const {error}=await client.from('questions').insert(row);msg('formMsg',error?error.message:'Question saved successfully.',false);if(!error){$('questionForm').reset();await loadQuestions();await loadStats()}};
function parseCSV(text){const rows=[];let row=[],cell='',quote=false;for(let i=0;i<text.length;i++){const ch=text[i],nx=text[i+1];if(ch==='"'&&quote&&nx==='"'){cell+='"';i++;continue}if(ch==='"'){quote=!quote;continue}if(ch===','&&!quote){row.push(cell);cell='';continue}if((ch==='\n'||ch==='\r')&&!quote){if(ch==='\r'&&nx==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))rows.push(row);row=[];continue}cell+=ch}if(cell||row.length){row.push(cell);rows.push(row)}return rows}
$('importCsv').onclick=async()=>{const f=$('csvFile').files[0];if(!f){msg('csvMsg','Choose a CSV file first.');return}const rows=parseCSV(await f.text());if(rows.length<2){msg('csvMsg','CSV has no data rows.');return}const headers=rows[0].map(x=>x.trim().toLowerCase());const objects=rows.slice(1).map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]||'').trim()])));const [er,sr]=await Promise.all([client.from('exams').select('id,name'),client.from('subjects').select('id,name')]);const exams=Object.fromEntries((er.data||[]).map(x=>[x.name.toLowerCase(),x.id]));const subjects=Object.fromEntries((sr.data||[]).map(x=>[x.name.toLowerCase(),x.id]));const payload=objects.filter(x=>x.question).map(x=>({question:x.question,option_a:x.option_a,option_b:x.option_b,option_c:x.option_c,option_d:x.option_d,answer:(x.answer||'A').toUpperCase(),explanation:x.explanation||'',exam_id:exams[(x.exam||'').toLowerCase()]||null,subject_id:subjects[(x.subject||'').toLowerCase()]||null,difficulty:x.difficulty||'Moderate',year:x.year?Number(x.year):null,tags:x.tags||'',status:x.status||'draft'}));const {error}=await client.from('questions').insert(payload);msg('csvMsg',error?error.message:`Imported ${payload.length} questions.`);if(!error){await loadQuestions();await loadStats()}};
$('caForm').onsubmit=async e=>{e.preventDefault();const row={title:$('caTitle').value,content:$('caContent').value,category:$('caCategory').value,published_date:$('caDate').value,is_published:$('caPublish').value==='true'};const {error}=await client.from('current_affairs').insert(row);msg('caMsg',error?error.message:'Current affair saved.');if(!error){$('caForm').reset();await loadCurrent();await loadStats()}};
async function loadCurrent(){const {data}=await client.from('current_affairs').select('title,category,published_date,is_published').order('published_date',{ascending:false}).limit(30);$('caRows').innerHTML=(data||[]).map(x=>`<tr><td>${esc(x.title)}</td><td>${esc(x.category||'')}</td><td>${x.published_date||''}</td><td>${x.is_published?'Yes':'No'}</td></tr>`).join('')||'<tr><td colspan="4">No current affairs yet.</td></tr>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
document.querySelectorAll('.admin-nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$('tab-'+b.dataset.tab).classList.remove('hidden')});
init();

// ===== Mock Test Builder =====
let mockQuestions=[]; let mockSelected=new Set();
async function loadMockBuilder(){
  const {data:exams}=await client.from('exams').select('id,name').order('name');
  $('mockExam').innerHTML=(exams||[]).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');
  const {data,error}=await client.from('questions').select('id,question,year,subjects(name),exams(name)').eq('status','published').order('created_at',{ascending:false}).limit(1000);
  if(error){msg('mockMsg',error.message);return}
  mockQuestions=data||[]; renderMockPicker(); await loadMockTests();
}
function renderMockPicker(){
  const term=($('mockSearch')?.value||'').toLowerCase().trim();
  const rows=mockQuestions.filter(q=>!term||q.question.toLowerCase().includes(term)||(q.subjects?.name||'').toLowerCase().includes(term)||(q.exams?.name||'').toLowerCase().includes(term));
  $('mockQuestionPicker').innerHTML=rows.map(q=>`<label class="mock-q ${mockSelected.has(q.id)?'selected':''}"><input type="checkbox" value="${q.id}" ${mockSelected.has(q.id)?'checked':''}><span><p>${esc(q.question)}</p><small>${esc(q.exams?.name||'')} • ${esc(q.subjects?.name||'')}${q.year?' • '+q.year:''}</small></span></label>`).join('')||'<div class="notice">No published questions found.</div>';
  $('mockQuestionPicker').querySelectorAll('input').forEach(cb=>cb.onchange=()=>{if(cb.checked)mockSelected.add(cb.value);else mockSelected.delete(cb.value);cb.closest('.mock-q').classList.toggle('selected',cb.checked);updateMockCount()});
  updateMockCount();
}
function updateMockCount(){if($('mockSelectedCount'))$('mockSelectedCount').textContent=`${mockSelected.size} question${mockSelected.size===1?'':'s'} selected`;}
$('mockSearch')?.addEventListener('input',renderMockPicker);
$('selectVisible')?.addEventListener('click',()=>{$('mockQuestionPicker').querySelectorAll('input').forEach(cb=>{mockSelected.add(cb.value);cb.checked=true;cb.closest('.mock-q').classList.add('selected')});updateMockCount()});
$('clearSelected')?.addEventListener('click',()=>{mockSelected.clear();renderMockPicker()});
$('mockForm')?.addEventListener('reset',()=>{setTimeout(()=>{mockSelected.clear();renderMockPicker()},0)});
async function loadMockTests(){
 const {data,error}=await client.from('mock_tests_v1').select('id,code,title,duration_minutes,total_questions,status,is_premium,exam_id,exams(name)').order('created_at',{ascending:false}).limit(100);
 if(error){msg('mockMsg',error.message);return}
 $('mockRows').innerHTML=(data||[]).map(t=>`<tr><td><b>${esc(t.title)}</b><div class="small">${esc(t.code)}</div></td><td>${esc(t.exams?.name||'')}</td><td>${t.total_questions}</td><td>${t.duration_minutes} min</td><td><span class="badge">${esc(t.status)}</span>${t.is_premium?' <span class="badge" style="background:#fff1e3;color:#c66509">PREMIUM</span>':''}</td><td><button class="btn light" onclick="setMockStatus('${t.id}','${t.status==='published'?'draft':'published'}')">${t.status==='published'?'Unpublish':'Publish'}</button></td></tr>`).join('')||'<tr><td colspan="6">No mock tests yet.</td></tr>';
}
window.setMockStatus=async(id,status)=>{const {error}=await client.from('mock_tests_v1').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)msg('mockMsg',error.message);else{msg('mockMsg',`Mock test ${status}.`);await loadMockTests()}};
$('mockForm')?.addEventListener('submit',async e=>{
 e.preventDefault(); const total=Number($('mockTotal').value); if(mockSelected.size!==total){msg('mockMsg',`Select exactly ${total} questions before saving. You currently selected ${mockSelected.size}.`);return}
 const {data:{user}}=await client.auth.getUser(); if(!user){msg('mockMsg','Login session expired.');return}
 const row={code:$('mockCode').value.trim(),title:$('mockTitle').value.trim(),description:$('mockDescription').value.trim()||null,exam_id:$('mockExam').value||null,duration_minutes:Number($('mockDuration').value),total_questions:total,marks_per_question:Number($('mockMarks').value),negative_mark:Number($('mockNegative').value||0),status:$('mockStatus').value,is_premium:$('mockAccess').value==='premium',created_by:user.id,updated_at:new Date().toISOString()};
 const ins=await client.from('mock_tests_v1').insert(row).select('id').single(); if(ins.error){msg('mockMsg',ins.error.message);return}
 const selected=[...mockSelected]; const links=selected.map((question_id,i)=>({mock_test_id:ins.data.id,question_id,question_order:i+1}));
 const link=await client.from('mock_test_questions_v1').insert(links); if(link.error){await client.from('mock_tests_v1').delete().eq('id',ins.data.id);msg('mockMsg','Test was not saved: '+link.error.message);return}
 msg('mockMsg',`Mock test “${row.title}” saved successfully.`); $('mockForm').reset(); await loadMockTests();
});
const _oldInit=init; init=async function(){await _oldInit(); if(!$('mockForm'))return; await loadMockBuilder();};
