(()=>{const cfg=window.AXOMPREP_CONFIG||{},sb=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey),$=id=>document.getElementById(id);let all=[],selected=new Set(),userId=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function csv(text){let R=[],r=[],c='',q=false;for(let i=0;i<text.length;i++){let ch=text[i],n=text[i+1];if(ch=='"'&&q&&n=='"'){c+='"';i++;continue}if(ch=='"'){q=!q;continue}if(ch==','&&!q){r.push(c);c='';continue}if((ch=='\n'||ch=='\r')&&!q){if(ch=='\r'&&n=='\n')i++;r.push(c);c='';if(r.some(x=>x.trim()))R.push(r);r=[];continue}c+=ch}if(c||r.length){r.push(c);R.push(r)}return R}
function objects(text){let R=csv(text);if(R.length<2)return[];let H=R[0].map(x=>x.trim().toLowerCase());return R.slice(1).map(row=>Object.fromEntries(H.map((h,i)=>[h,(row[i]||'').trim()])))}
function normTag(s){return String(s||'').split(',').map(x=>x.trim()).filter(Boolean)}
function isReview(r){return String(r.verification_status||'').toUpperCase()!='VERIFIED'}
function show(msg){$('notice').textContent=msg;$('notice').classList.add('show')}
function hide(){ $('notice').classList.remove('show') }
async function auth(){const {data:{user},error}=await sb.auth.getUser();if(error||!user){location.href='index.html#login';return false}const {data:p}=await sb.from('profiles').select('role').eq('id',user.id).maybeSingle();if(p?.role!=='admin'){show('Admin access required.');return false}userId=user.id;return true}
function render(){let scope=$('scope').value;let view=scope==='ready'?all.filter(r=>!isReview(r)):scope==='review'?all.filter(isReview):all;let ids=new Set(view.map(r=>r.__id));selected=new Set([...selected].filter(id=>ids.has(id)));$('rows').innerHTML=view.length?view.map(r=>`<tr><td><input type="checkbox" class="pick" data-id="${r.__id}" ${selected.has(r.__id)?'checked':''}></td><td>${esc(r.paper)}</td><td>${esc(r.question_no)}</td><td class="q">${esc(r.question)}</td><td>${esc(r.exam)}</td><td>${esc(r.year)}</td><td><b>${esc(r.answer)}</b></td><td>${isReview(r)?'<span class="badge review">NEEDS_REVIEW</span>':'<span class="badge ok">VERIFIED</span>'}</td></tr>`).join(''):'<tr><td colspan="8" class="empty">No rows in this scope.</td></tr>';updateCount()}
function updateCount(){$('progressText').textContent=`${selected.size} selected`}
async function loadFile(f){hide();let arr=objects(await f.text());if(!arr.length){show('CSV contains no data rows.');return}
all=arr.map((r,i)=>({...r,__id:String(i)}));let ready=all.filter(r=>!isReview(r)).length;$('total').textContent=all.length;$('ready').textContent=ready;$('needs').textContent=all.length-ready;$('dupes').textContent=findDupes().size;$('importPanel').style.display='block';$('scope').value='ready';selected.clear();render()}
function key(r){return [r.question,r.option_a,r.option_b,r.option_c,r.option_d,r.exam,r.year].map(x=>String(x||'').toLowerCase().trim()).join('|')}
function findDupes(){let seen=new Set(),dup=new Set();for(const r of all){let k=key(r);if(seen.has(k))dup.add(k);else seen.add(k)}return dup}
async function existingDupes(rows){let q=rows.map(key),out=new Set(); // batch approximate using exact question text checks
let qs=[...new Set(rows.map(r=>r.question).filter(Boolean))];for(let i=0;i<qs.length;i+=50){let part=qs.slice(i,i+50);const {data,error}=await sb.from('questions').select('id,question,year').in('question',part);if(error)console.warn(error);(data||[]).forEach(x=>out.add(`${String(x.question).toLowerCase().trim()}|${x.year||''}`))}return out}
async function doImport(){let chosen=all.filter(r=>selected.has(r.__id));if(!chosen.length)return show('Select at least one row.');hide();$('import').disabled=true;let ext=await existingDupes(chosen);let payload=[],skipped=0;for(const r of chosen){let k=`${String(r.question||'').toLowerCase().trim()}|${r.year||''}`;if(ext.has(k)){skipped++;continue}let tags=normTag(r.tags);if(!tags.some(t=>t.toUpperCase()==='PYQ'))tags.push('PYQ');if(r.exam)tags.push('ADRE 2024',r.paper||'');let clean=[...new Set(tags.filter(Boolean))];payload.push({question:r.question,option_a:r.option_a,option_b:r.option_b,option_c:r.option_c,option_d:r.option_d,answer:(r.answer||'A').toUpperCase(),explanation:r.explanation||null,exam_id:null,subject_id:null,topic_id:null,difficulty:(r.difficulty||'medium').toLowerCase(),year:r.year?Number(r.year):null,tags:clean,status:$('status').value,created_by:userId})}
// Resolve exam id by name
const {data:exams,error:ee}=await sb.from('exams').select('id,name');if(ee){$('import').disabled=false;return show(ee.message)}const em=Object.fromEntries((exams||[]).map(x=>[x.name.toLowerCase(),x.id]));payload.forEach((p,i)=>{let src=chosen[i];p.exam_id=em[String(src.exam||'').toLowerCase()]||null});
// Subject/topic resolution when exact names exist
const {data:subs}=await sb.from('subjects').select('id,name');const sm=Object.fromEntries((subs||[]).map(x=>[x.name.toLowerCase(),x.id]));
payload.forEach((p,i)=>{let src=chosen[i];p.subject_id=sm[String(src.subject||'').toLowerCase()]||null});
let ok=0;for(let i=0;i<payload.length;i+=50){$('prog').style.width=`${Math.round(i/payload.length*100)}%`;const {error}=await sb.from('questions').insert(payload.slice(i,i+50));if(error){console.error(error);$('import').disabled=false;$('prog').style.width='0';return show(`Import stopped: ${error.message}. Imported ${ok} before the error.`)}ok+=Math.min(50,payload.length-i)}
$('prog').style.width='100%';$('import').disabled=false;show(`Import complete: ${ok} inserted, ${skipped} skipped as existing duplicates.`)}
$('file').onchange=e=>e.target.files[0]&&loadFile(e.target.files[0]);$('drop').ondragover=e=>{e.preventDefault();$('drop').classList.add('drag')};$('drop').ondragleave=()=>$('drop').classList.remove('drag');$('drop').ondrop=e=>{e.preventDefault();$('drop').classList.remove('drag');let f=e.dataTransfer.files[0];if(f)loadFile(f)};
$('scope').onchange=render;$('selectReady').onclick=()=>{selected=new Set(all.filter(r=>!isReview(r)).map(r=>r.__id));render()};$('selectAll').onclick=()=>{let view=$('scope').value==='ready'?all.filter(r=>!isReview(r)):$('scope').value==='review'?all.filter(isReview):all;selected=new Set(view.map(r=>r.__id));render()};$('clearSel').onclick=()=>{selected.clear();render()};$('rows').onclick=e=>{if(e.target.classList.contains('pick')){let id=e.target.dataset.id;e.target.checked?selected.add(id):selected.delete(id);updateCount()}};
$('import').onclick=doImport;$('logout').onclick=async()=>{await sb.auth.signOut();location.href='index.html'};
(async()=>{await auth()})();})()